name: "Deploy Akamai Edgeworkers"
description: "GitHub Action to edgerworkers via Akamai API's"
author: jdmevo123
inputs:
  edgeworkersName:
    description:  'Name of Edgeworker'
    required: true
  network:
    description: 'Network you wish to activate'
    required: true
    default: 'staging'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.edgeworkersName}}
    - ${{ inputs.network }}
branding:
  color: orange
  icon: trash-2
