name: "Deploy Akamai Edgeworkers"
description: "GitHub Action to edgerworkers via Akamai API's"
author: Achuthananda M P
inputs:
  edgeworkersId:
    description:  'Edgeworker Id'
    required: true
  network:
    description: 'Network you wish to activate'
    required: true
    default: 'staging'
  groupid:
    description: 'GroupID for new registrations'
    required: true
  accountSwitchKey:
    description: 'Account SwitchKey'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.edgeworkersId}}
    - ${{ inputs.network }}
    - ${{ inputs.groupid }}
    - ${{ inputs.accountSwitchKey }}
branding:
  color: orange
  icon: cloud-lightning
